# Generated by Django 2.1.5 on 2019-02-25 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'brands',
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'color',
                'verbose_name_plural': 'colors',
                'db_table': 'color',
            },
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'verbose_name': 'ram',
                'verbose_name_plural': 'ram',
                'db_table': 'ram',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'store',
                'verbose_name_plural': 'stores',
                'db_table': 'store',
            },
        ),
        migrations.RemoveField(
            model_name='internalmemory',
            name='phone',
        ),
        migrations.DeleteModel(
            name='Website',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='color',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='ram',
        ),
        migrations.DeleteModel(
            name='InternalMemory',
        ),
        migrations.AddField(
            model_name='store',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone.Phone'),
        ),
        migrations.AddField(
            model_name='ram',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone.Phone'),
        ),
        migrations.AddField(
            model_name='color',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone.Phone'),
        ),
        migrations.AddField(
            model_name='brand',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone.Phone'),
        ),
    ]
