# Generated by Django 2.1.5 on 2019-03-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0004_auto_20190304_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='allowed_laguages',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('ar', 'Arabic'), ('fr', 'French')], max_length=100, null=True),
        ),
    ]
