# Generated by Django 2.1.5 on 2019-03-31 12:16

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0007_auto_20190304_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='language_code',
        ),
        migrations.AddField(
            model_name='country',
            name='country_banner',
            field=models.ImageField(max_length=255, null=True, upload_to='', verbose_name='Country Banner Image'),
        ),
        migrations.AddField(
            model_name='country',
            name='country_code',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Country Code'),
        ),
        migrations.AddField(
            model_name='country',
            name='country_flag',
            field=models.ImageField(max_length=255, null=True, upload_to='', verbose_name='Country Flag Image'),
        ),
        migrations.AddField(
            model_name='country',
            name='country_full_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='country',
            name='currency',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('en', 'Algerian dinar'), ('ar', 'Bahraini dinar'), ('fr1', 'Egyptian pound'), ('en', 'Iraqi dinar'), ('arw', 'Jordanian dinar'), ('frs', 'Kuwaiti dinar'), ('ena', 'Lebanese pound'), ('arc', 'Libyan dinar'), ('frc', 'Moroccan dirham'), ('eng', 'Omani rial'), ('ent', 'Palestine pound'), ('arg', 'Qatari riyal'), ('frn', 'Saudi riyal'), ('frm', 'Sudanese pound'), ('en5', 'Syrian pound'), ('ar9', 'Tunisian dinar'), ('frv', 'United Arab Emirates dirham'), ('enb', 'Yemeni rial'), ('USD', 'United States Dollar'), ('frx', 'Euro'), ('frl', 'GBP')], max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Short Name'),
        ),
    ]
