# Generated by Django 2.1.5 on 2019-02-06 12:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_auto_20190205_1254'),
        ('mailchimp', '0002_mailchimp_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailScheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheduled_start', models.DateTimeField()),
                ('frequency', models.IntegerField(default=1, help_text='No of mail per day to Advertisers related to one advertisement .', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MinValueValidator(3)], verbose_name='Frequency')),
                ('advertisement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='advertisement.Ad', verbose_name='Advertisement')),
            ],
        ),
    ]
