# Generated by Django 2.1.5 on 2019-02-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailchimp', '0003_emailscheduler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailscheduler',
            name='sheduled_start',
            field=models.DateTimeField(verbose_name='Alert Scheduled'),
        ),
    ]
