# Generated by Django 2.1.5 on 2019-02-06 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailchimp', '0004_auto_20190206_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailscheduler',
            name='frequency',
            field=models.IntegerField(default=1, help_text='No of mail per day to Advertisers related to one advertisement .', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='emailscheduler',
            name='sheduled_start',
            field=models.DateTimeField(verbose_name='Alert Scheduled From'),
        ),
    ]
