# Generated by Django 2.1.5 on 2019-03-07 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailchimp', '0006_auto_20190207_1359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailchimp',
            options={'verbose_name': 'Mail Campaign', 'verbose_name_plural': 'Mail Campaign'},
        ),
    ]
