# Generated by Django 2.1.5 on 2019-02-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='page',
            field=models.CharField(choices=[('Phone', 'Phone'), ('Plan', 'Plan'), ('MobilePlan', 'MobilePlan')], default='Phone', max_length=12, verbose_name='Page'),
        ),
    ]
