# Generated by Django 2.1.5 on 2019-02-05 12:32

import advertisement.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('url', models.URLField(verbose_name='Advertised URL')),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start showing')),
                ('publication_date_end', models.DateTimeField(default=advertisement.models.now_plus_1_day, verbose_name='Stop showing')),
                ('zone', models.CharField(max_length=100, verbose_name='Zone')),
                ('weight', models.IntegerField(default=1, help_text='Weight of the ad relative to other ads in the same zone.<br />Ad with higher weight will be displayed more frequently.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Weight')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Manage Advertisement',
                'verbose_name_plural': 'Manage Advertisements',
            },
        ),
        migrations.CreateModel(
            name='AdImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(choices=[('xs', '720x150'), ('sm', '800x90'), ('md', '800x90'), ('lg', '800x90')], max_length=2, verbose_name='Device')),
                ('image', models.ImageField(max_length=255, upload_to='', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('website', models.URLField(verbose_name='Company Site')),
            ],
            options={
                'verbose_name': 'Manage Advertiser',
                'verbose_name_plural': 'Manage Advertisers',
                'ordering': ('company_name',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Manage Category',
                'verbose_name_plural': 'Manage Categories',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_date', models.DateTimeField(auto_now_add=True, verbose_name='When')),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Source IP Address')),
                ('session_id', models.CharField(blank=True, max_length=40, null=True, verbose_name='Source Session ID')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='advertisement.Ad', verbose_name='Ad')),
            ],
            options={
                'verbose_name': 'View Advertisement Click',
                'verbose_name_plural': 'View Advertisement Clicks',
            },
        ),
        migrations.CreateModel(
            name='Impression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impression_date', models.DateTimeField(auto_now_add=True, verbose_name='When')),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Source IP Address')),
                ('session_id', models.CharField(blank=True, max_length=40, null=True, verbose_name='Source Session ID')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='advertisement.Ad', verbose_name='Ad')),
            ],
            options={
                'verbose_name': 'View Advertisement Impression',
                'verbose_name_plural': 'View Advertisement Impressions',
            },
        ),
    ]
