# Generated by Django 2.1.5 on 2019-02-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_auto_20190205_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adimage',
            name='device',
            field=models.CharField(choices=[('xs', '720x150'), ('sm', '375x50'), ('md', '414x736'), ('lg', '800x90')], max_length=2, verbose_name='Device'),
        ),
    ]
