# Generated by Django 2.1.5 on 2019-02-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_auto_20190205_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiser',
            name='email',
            field=models.EmailField(default='admin@admin.com', max_length=254, unique=True, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
