# Generated by Django 2.1.5 on 2019-02-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0004_advertiser_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'verbose_name': 'Advertisement', 'verbose_name_plural': 'Manage Advertisements'},
        ),
        migrations.AlterModelOptions(
            name='advertiser',
            options={'ordering': ('company_name',), 'verbose_name': 'Advertiser', 'verbose_name_plural': 'Manage Advertisers'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('title',), 'verbose_name': 'Category', 'verbose_name_plural': 'Manage Categories'},
        ),
        migrations.AlterModelOptions(
            name='click',
            options={'verbose_name': 'Advertisement Click', 'verbose_name_plural': 'View Advertisement Clicks'},
        ),
        migrations.AlterModelOptions(
            name='impression',
            options={'verbose_name': 'Advertisement Impression', 'verbose_name_plural': 'View Advertisement Impressions'},
        ),
        migrations.AddField(
            model_name='ad',
            name='page',
            field=models.CharField(choices=[('Phone', 'Phone'), ('Plan', 'Plan'), ('MobilePlan', 'MobilePlan')], default='Phone', max_length=12, verbose_name='Page'),
        ),
    ]
