# Generated by Django 2.1.5 on 2019-02-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0005_auto_20190207_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='page',
            field=models.CharField(max_length=100, verbose_name='Pages'),
        ),
    ]
