# Generated by Django 2.1.5 on 2019-03-04 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0006_auto_20190212_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(max_length=255, upload_to='', verbose_name='Video')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='advertisement.Ad', verbose_name='Ad')),
            ],
        ),
    ]
