# Generated by Django 2.1.5 on 2019-02-22 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='adsl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_type', models.CharField(blank=True, max_length=10, null=True)),
                ('pay_type_en', models.CharField(blank=True, max_length=10, null=True)),
                ('pay_type_ar', models.CharField(blank=True, max_length=10, null=True)),
                ('line_type', models.CharField(blank=True, max_length=10, null=True)),
                ('line_type_en', models.CharField(blank=True, max_length=10, null=True)),
                ('line_type_ar', models.CharField(blank=True, max_length=10, null=True)),
                ('monthly_payment', models.CharField(blank=True, max_length=10, null=True)),
                ('monthly_payment_en', models.CharField(blank=True, max_length=10, null=True)),
                ('monthly_payment_ar', models.CharField(blank=True, max_length=10, null=True)),
                ('payment_note', models.CharField(blank=True, max_length=10, null=True)),
                ('payment_note_en', models.CharField(blank=True, max_length=10, null=True)),
                ('payment_note_ar', models.CharField(blank=True, max_length=10, null=True)),
                ('upfront_payment_option_for_three_month', models.CharField(blank=True, max_length=10, null=True)),
                ('upfront_payment_option_for_six_month', models.CharField(blank=True, max_length=10, null=True)),
                ('upfront_payment_option_for_twelve_month', models.CharField(blank=True, max_length=10, null=True)),
                ('download_speed', models.CharField(blank=True, max_length=10, null=True)),
                ('upload_speed', models.CharField(blank=True, max_length=10, null=True)),
                ('months', models.IntegerField(blank=True, null=True)),
                ('free_months', models.IntegerField(blank=True, null=True)),
                ('benefits', models.CharField(blank=True, max_length=10, null=True)),
                ('benefits_en', models.CharField(blank=True, max_length=10, null=True)),
                ('benefits_ar', models.CharField(blank=True, max_length=10, null=True)),
                ('english_url', models.CharField(blank=True, max_length=500, null=True)),
                ('arabic_url', models.CharField(blank=True, max_length=500, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone.Country')),
            ],
            options={
                'verbose_name': 'ADSL plan',
                'verbose_name_plural': 'ADSL plans',
                'db_table': 'adsl',
            },
        ),
    ]
