"""
Django settings for planbaker project.

Generated by 'django-admin startproject' using Django 2.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""
from django.utils.translation import ugettext_lazy as _
import os
import environ
import dotenv

env = environ.Env()
dotenv.load_dotenv(
    os.path.join(os.path.dirname(os.path.dirname(__file__)), '.env')
)

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG')

ALLOWED_HOSTS = ['*']
FORM_RENDERER = 'django.forms.renderers.TemplatesSetting'
MAILCHIMP_API_KEY = env.str('MAILCHIMP_API_KEY')
MAILCHIMP_DATA_CENTER = env.str('MAILCHIMP_DATA_CENTER')
MAILCHIMP_EMAIL_LIST_ID = env.str('MAILCHIMP_EMAIL_LIST_ID')

# Application definition
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.webfaction.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'planbaker_sayone'
DEFAULT_FROM_EMAIL = 'planbaker@sayonetech.com'
EMAIL_HOST_PASSWORD = ''

ALPHA_CURRENCY_KEY = ''

INSTALLED_APPS = [
    'modeltranslation',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'multiselectfield',
    'django.forms',
    'user',
    'advertisement',
    'phone',
    'plan',
    'adsl',
    'sekizai',
    'mailchimp',
    'survey',
    'pages',
    'affiliate_marketing',
    'mobile_internet',
    'fixed_internet',
    'el_pagination',
    'connekio'



]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'middleware.find_location.IpMiddleWare',
    'middleware.template_middleware.TemplateMiddleWare',
]

ROOT_URLCONF = 'planbaker.urls'

AUTH_USER_MODEL = 'user.User'

LOCALE_PATHS = (os.path.join(BASE_DIR, "locale"),)

gettext = lambda s: s

LANGUAGES = (
    ('en', gettext('English')),
    ('ar', gettext('Arabic')),
    ('fr', gettext('French')),

)
LOADING = """<div class='load_more_div'><div class='container'><div class='load_more_btn_div'>
<button class='load_more_btn btn'>Loading...</button></div></div></div>"""
EL_PAGINATION_LOADING = """<div class='load_more_div'> <div class='load_more_btn_div'><button class='load_more_btn btn'>Loading...</button></div></div>"""
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [

                'context_processor.processors.locale',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',

            ],
        },
    },
]

WSGI_APPLICATION = 'planbaker.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': env.str('DB_ENGINE'),
        'NAME': env.str('DB_NAME'),
        'USER': env.str('DB_USER'),
        'PASSWORD': env.str('DB_PASSWORD'),
        'HOST': env.str('DB_HOST'),
        'PORT': env.int('DB_PORT', default=5432),
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/


TIME_ZONE = 'Asia/Riyadh'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
# Extra places for collectstatic to find static files.
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

MODELTRANSLATION_TRANSLATION_FILES = (
    'phone.translation',
    'plan.translation',
    'adsl.translation',

)

MODELTRANSLATION_DEBUG = True
ACCOUNT_SECURITY_API_KEY = ''

GOOGLE_RECAPTCHA_SECRET_KEY = ''


