# Generated by Django 2.1.5 on 2019-04-05 09:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceInstallment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_value', models.IntegerField(blank=True, null=True, verbose_name='Installment Value')),
                ('device_upfront_otp', models.IntegerField(blank=True, null=True, verbose_name='Device Upfront One Time Payment')),
                ('commitment_months', models.IntegerField(blank=True, default=0, null=True, verbose_name='Commitment Months/Contract Period')),
                ('device_url_english', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Buy Online English URL')),
                ('device_url_arabic', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Buy Online Arabic URL')),
                ('device_url_english_near', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Nearest Store English URL')),
                ('device_url_arabic_near', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Nearest Store Arabic URL')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_installment_device', to='plan.DeviceRam')),
            ],
            options={
                'verbose_name': 'Device Instalment Configuration',
                'verbose_name_plural': 'Device Instalment Configurations',
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='plan_url_arabic_near',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Nearest Store Arabic URL'),
        ),
        migrations.AddField(
            model_name='plan',
            name='plan_url_english_near',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Nearest Store English URL'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_url_arabic',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Buy Online Arabic URL'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_url_english',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Buy Online English URL'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='publication_date_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 4, 9, 33, 38, 631699, tzinfo=utc), verbose_name='Deactivate Plan on:'),
        ),
        migrations.AddField(
            model_name='deviceinstallment',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_installment_plan', to='plan.Plan'),
        ),
    ]
