# Generated by Django 2.1.5 on 2019-04-09 06:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_auto_20190409_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='add_free_internet',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Additional free Internet Quota (MB)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='publication_date_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 6, 53, 23, 869156, tzinfo=utc), verbose_name='Deactivate Plan on:'),
        ),
    ]
