# Generated by Django 2.1.5 on 2019-04-11 12:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0007_auto_20190409_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='publication_date_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 10, 12, 2, 27, 97544, tzinfo=utc), verbose_name='Deactivate Plan on:'),
        ),
    ]
