# Generated by Django 2.1.5 on 2019-04-12 09:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0012_country_is_active'),
        ('plan', '0009_auto_20190412_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinstallment',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='phone.Country'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='publication_date_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 11, 9, 57, 6, 752523, tzinfo=utc), verbose_name='Deactivate Plan on:'),
        ),
    ]
