# Generated by Django 2.1.5 on 2019-04-12 11:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0010_auto_20190412_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='publication_date_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 11, 11, 41, 10, 153344, tzinfo=utc), verbose_name='Deactivate Plan on:'),
        ),
    ]
