# Generated by Django 2.1.5 on 2019-04-16 06:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0011_auto_20190412_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceinstallment',
            name='device_upfront_otp',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Device Upfront One Time Payment'),
        ),
        migrations.AlterField(
            model_name='deviceinstallment',
            name='installment_value',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Installment Value'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='publication_date_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 6, 50, 6, 300536, tzinfo=utc), verbose_name='Deactivate Plan on:'),
        ),
    ]
