# Generated by Django 2.1.5 on 2019-04-22 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0013_auto_20190417_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='publication_date_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deactivate Plan on:'),
        ),
    ]
