# Generated by Django 2.1.5 on 2019-04-22 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0014_auto_20190422_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceram',
            name='device_phone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_ram_plan_phone', to='plan.PlanPhone', verbose_name='Plan Device'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_url_arabic',
            field=models.CharField(max_length=1000, null=True, verbose_name='Buy Online Arabic URL'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_url_arabic_near',
            field=models.CharField(max_length=1000, null=True, verbose_name='Nearest Store Arabic URL'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_url_english',
            field=models.CharField(max_length=1000, null=True, verbose_name='Buy Online English URL'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_url_english_near',
            field=models.CharField(max_length=1000, null=True, verbose_name='Nearest Store English URL'),
        ),
    ]
