# Generated by Django 2.1.5 on 2019-04-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0015_auto_20190422_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalbenefit',
            name='benefits_ar',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Benefits'),
        ),
        migrations.AddField(
            model_name='additionalbenefit',
            name='benefits_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Benefits'),
        ),
        migrations.AddField(
            model_name='additionalbenefit',
            name='benefits_fr',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Benefits'),
        ),
        migrations.AddField(
            model_name='additionalbenefit',
            name='contract_renewal_benefits_ar',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Contract Renewal Benefits'),
        ),
        migrations.AddField(
            model_name='additionalbenefit',
            name='contract_renewal_benefits_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Contract Renewal Benefits'),
        ),
        migrations.AddField(
            model_name='additionalbenefit',
            name='contract_renewal_benefits_fr',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Contract Renewal Benefits'),
        ),
        migrations.AddField(
            model_name='additionalbenefit',
            name='device_discount_benefits_ar',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Device discount Benefit'),
        ),
        migrations.AddField(
            model_name='additionalbenefit',
            name='device_discount_benefits_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Device discount Benefit'),
        ),
        migrations.AddField(
            model_name='additionalbenefit',
            name='device_discount_benefits_fr',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Device discount Benefit'),
        ),
        migrations.AddField(
            model_name='additionalbenefit',
            name='other_benefits_ar',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Other benefits'),
        ),
        migrations.AddField(
            model_name='additionalbenefit',
            name='other_benefits_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Other benefits'),
        ),
        migrations.AddField(
            model_name='additionalbenefit',
            name='other_benefits_fr',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Other benefits'),
        ),
        migrations.AddField(
            model_name='additionalbenefit',
            name='special_number_benefits_ar',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Special Number Benefits'),
        ),
        migrations.AddField(
            model_name='additionalbenefit',
            name='special_number_benefits_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Special Number Benefits'),
        ),
        migrations.AddField(
            model_name='additionalbenefit',
            name='special_number_benefits_fr',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Special Number Benefits'),
        ),
        migrations.AddField(
            model_name='additionalbenefit',
            name='welcome_package_benefits_ar',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='welcome package Benefits'),
        ),
        migrations.AddField(
            model_name='additionalbenefit',
            name='welcome_package_benefits_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='welcome package Benefits'),
        ),
        migrations.AddField(
            model_name='additionalbenefit',
            name='welcome_package_benefits_fr',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='welcome package Benefits'),
        ),
    ]
