# Generated by Django 2.1.5 on 2019-04-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0016_auto_20190424_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plandevice',
            name='contract_period',
        ),
        migrations.RemoveField(
            model_name='plandevice',
            name='device_upfront_otp',
        ),
        migrations.RemoveField(
            model_name='plandevice',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='plandevice',
            name='installment_value',
        ),
        migrations.RemoveField(
            model_name='planphone',
            name='contract_period',
        ),
        migrations.RemoveField(
            model_name='planphone',
            name='device_upfront_otp',
        ),
        migrations.RemoveField(
            model_name='planphone',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='planphone',
            name='installment_value',
        ),
        migrations.AddField(
            model_name='deviceinstallment',
            name='discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Discount in %'),
        ),
        migrations.AddField(
            model_name='plandevice',
            name='brand_ar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='plandevice',
            name='brand_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='plandevice',
            name='brand_fr',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='plandevice',
            name='name_ar',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='plandevice',
            name='name_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='plandevice',
            name='name_fr',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='plandevice',
            name='title_ar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='plandevice',
            name='title_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='plandevice',
            name='title_fr',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='planphone',
            name='brand_ar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='planphone',
            name='brand_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='planphone',
            name='brand_fr',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='planphone',
            name='name_ar',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='planphone',
            name='name_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='planphone',
            name='name_fr',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='planphone',
            name='title_ar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='planphone',
            name='title_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='planphone',
            name='title_fr',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
