# Generated by Django 2.1.5 on 2019-04-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0017_auto_20190424_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='planphoneconnectivityattribute',
            name='gps',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='GPS'),
        ),
        migrations.AddField(
            model_name='planphoneconnectivityattribute',
            name='radio',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='radio'),
        ),
        migrations.AddField(
            model_name='planphonegeneralattribute',
            name='chip_set',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Chip set'),
        ),
        migrations.AddField(
            model_name='planphonegeneralattribute',
            name='cpu',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='CPU'),
        ),
        migrations.AddField(
            model_name='planphonegeneralattribute',
            name='released',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Release Date:'),
        ),
    ]
