# Generated by Django 2.1.5 on 2019-04-26 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0018_auto_20190424_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinstallment',
            name='line_type',
            field=models.CharField(blank=True, choices=[('voice', 'VOICE'), ('internet', 'INTERNET')], max_length=50, null=True, verbose_name='Line Type'),
        ),
        migrations.AddField(
            model_name='deviceinstallment',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.operators', verbose_name='Operators'),
        ),
    ]
