# Generated by Django 2.1.5 on 2019-04-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0019_auto_20190426_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinstallment',
            name='mf_method',
            field=models.CharField(blank=True, choices=[('MF1', 'MF1'), ('MF2', 'MF2')], help_text='<p>MF1 = <b>Package Fees</b><br/> MF2 = <b>Package Fees + Device Installment Value</b><br/> <br/>', max_length=10, null=True, verbose_name='Monthly Fees Calculation Method'),
        ),
        migrations.AddField(
            model_name='deviceinstallment',
            name='otp_method',
            field=models.CharField(blank=True, choices=[('OTP1', 'OTP1'), ('OTP2', 'OTP2'), ('OTP3', 'OTP3')], help_text='<p>OTP1 = <b>Package One Time Setup Fees</b><br/> OTP2 = <b>Package One Time Setup Fees + Device Upfront One Time Payment</b><br/> OTP3= <b>Package One Time Setup Fees +  2 x(Package Fees) +2 x (Device Installment Value)</b> <br/>', max_length=10, null=True, verbose_name='One Time payment Calculation Method'),
        ),
    ]
