# Generated by Django 2.1.5 on 2019-05-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0020_auto_20190430_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('expression', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Calculation Method',
                'verbose_name_plural': 'Calculation Methods',
                'db_table': 'calculationMethod',
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='mf',
            field=models.CharField(blank=True, choices=[('MF1', 'MF1'), ('MF2', 'MF2')], help_text='<p>MF1 = <b>Package Fees</b><br/> MF2 = <b>Package Fees + Device Installment Value</b><br/> <br/>', max_length=10, null=True, verbose_name='Monthly Fees Calculation Method'),
        ),
        migrations.AddField(
            model_name='plan',
            name='otp',
            field=models.CharField(blank=True, choices=[('OTP1', 'OTP1'), ('OTP2', 'OTP2'), ('OTP3', 'OTP3')], help_text='<p>OTP1 = <b>Package One Time Setup Fees</b><br/> OTP2 = <b>Package One Time Setup Fees + Device Upfront One Time Payment</b><br/> OTP3= <b>Package One Time Setup Fees +  2 x(Package Fees) +2 x (Device Installment Value)</b> <br/>', max_length=10, null=True, verbose_name='One Time payment Calculation Method'),
        ),
    ]
