# Generated by Django 2.1.5 on 2019-03-07 14:31

from django.db import migrations, models
import user.managers


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0072_auto_20190306_1720'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user.managers.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHERS', 'Others')], default='MALE', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_operator',
            field=models.CharField(blank=True, choices=[('OPERATOR1', 'OPERATOR1'), ('OPERATOR2', 'OPERATOR2'), ('OPERATOR3', 'OPERATOR3')], default='OPERATOR1', max_length=60),
        ),
    ]
