# Generated by Django 2.1.5 on 2019-03-10 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0074_auto_20190308_1604'),
        ('user', '0046_auto_20190310_0254'),
    ]

    operations = [
    ]
