# Generated by Django 2.1.5 on 2019-03-11 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0076_auto_20190308_1704'),
        ('user', '0084_auto_20190310_1955'),
    ]

    operations = [
    ]
