# Generated by Django 2.1.5 on 2019-03-12 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0096_auto_20190312_1613'),
        ('user', '0094_auto_20190312_1218'),
    ]

    operations = [
    ]
