# Generated by Django 2.1.5 on 2019-03-13 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0098_auto_20190313_0712'),
        ('user', '0097_merge_20190312_1623'),
    ]

    operations = [
    ]
