# Generated by Django 2.1.5 on 2019-05-09 10:02

from django.db import migrations, models
import user.managers


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0142_auto_20190503_0937'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user.managers.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_operator',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
