# Generated by Django 2.1.5 on 2019-02-22 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_url', models.CharField(blank=True, max_length=500, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='phone.Country')),
            ],
            options={
                'verbose_name': 'survey',
                'verbose_name_plural': 'Manage surveys',
                'db_table': 'survey',
            },
        ),
    ]
