# Generated by Django 2.1.5 on 2019-04-05 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('phone', '0010_phonecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedInternet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('pay_type', models.CharField(blank=True, choices=[('postpaid', 'POSTPAID'), ('prepaid', 'PREPAID')], max_length=50, null=True, verbose_name='pay type')),
                ('line_type', models.CharField(blank=True, choices=[('voice', 'VOICE'), ('internet', 'INTERNET')], max_length=50, null=True, verbose_name='line type')),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('short_description', models.TextField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, choices=[('branch', 'Go To nearest Branch'), ('online', 'Buy Online')], max_length=50, null=True, verbose_name='e-commerce status')),
                ('monthly_fee', models.IntegerField(blank=True, default=0, null=True, verbose_name='Monthly Fee')),
                ('fee_notes', models.CharField(blank=True, max_length=500, null=True)),
                ('upfront_payment_per_year', models.IntegerField(blank=True, null=True, verbose_name='Upfront payment yearly')),
                ('upfront_payment_half_yearly', models.IntegerField(blank=True, null=True, verbose_name='Upfront payment for 6 months')),
                ('upfront_payment_quarterly', models.IntegerField(blank=True, null=True, verbose_name='Upfront payment for 3 months')),
                ('download_speed', models.IntegerField(blank=True, null=True, verbose_name='Download Speed in KBPS')),
                ('upload_speed', models.IntegerField(blank=True, null=True, verbose_name='Upload Speed in KBPS')),
                ('data_quota', models.IntegerField(blank=True, null=True, verbose_name='Data Quota')),
                ('benefits', models.TextField(blank=True, max_length=1000, null=True)),
                ('english_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('arabic_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('available_for', models.CharField(blank=True, max_length=150, null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='phone.Country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Fixed Internet Plan',
                'verbose_name_plural': 'Fixed Internet Plans',
            },
        ),
    ]
