# Generated by Django 2.1.5 on 2019-04-05 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fixed_internet', '0001_initial'),
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedinternet',
            name='operator_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.operators', verbose_name='Operator'),
        ),
    ]
