# Generated by Django 2.1.5 on 2019-04-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_internet', '0003_auto_20190424_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixedinternet',
            name='arabic_url',
        ),
        migrations.RemoveField(
            model_name='fixedinternet',
            name='english_url',
        ),
        migrations.AddField(
            model_name='fixedinternet',
            name='nearest_branch_url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Go To the Nearest Branch URL'),
        ),
        migrations.AddField(
            model_name='fixedinternet',
            name='nearest_branch_url_ar',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Go To the Nearest Branch URL'),
        ),
        migrations.AddField(
            model_name='fixedinternet',
            name='nearest_branch_url_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Go To the Nearest Branch URL'),
        ),
        migrations.AddField(
            model_name='fixedinternet',
            name='nearest_branch_url_fr',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Go To the Nearest Branch URL'),
        ),
        migrations.AddField(
            model_name='fixedinternet',
            name='online_url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Buy Online URL'),
        ),
        migrations.AddField(
            model_name='fixedinternet',
            name='online_url_ar',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Buy Online URL'),
        ),
        migrations.AddField(
            model_name='fixedinternet',
            name='online_url_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Buy Online URL'),
        ),
        migrations.AddField(
            model_name='fixedinternet',
            name='online_url_fr',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Buy Online URL'),
        ),
    ]
