# Generated by Django 2.1.5 on 2019-02-19 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_user', models.CharField(max_length=255, verbose_name='End User')),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='User IP Address')),
                ('user_session', models.CharField(blank=True, max_length=40, null=True, verbose_name='User Session ID')),
                ('product_id', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Product Viewed',
                'verbose_name_plural': 'Products Viewed',
                'ordering': ['-timestamp'],
            },
        ),
    ]
